In [1]:
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score
import joblib

iris = datasets.load_iris()
x = iris.data
y = iris.target
y_names = iris.target_names

np.random.seed(26322)
test_ids = np.random.permutation(len(x))

x_train = x[test_ids[:-10]]
x_test = x[test_ids[-10:]]

y_train = y[test_ids[:-10]]
y_test = y[test_ids[-10:]]

# Árvore de decisão

In [2]:
from sklearn import tree
dtc = tree.DecisionTreeClassifier()
dtc.fit(x_train, y_train)
pred = dtc.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(dtc, "iris_dtc_1.0.joblib")

[0 2 0 1 0 0 2 1 0 2]
[0 2 0 1 0 0 2 1 0 2]
100.0


['iris_dtc_1.0.joblib']

# Naive Bayes

In [3]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
pred = gnb.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(gnb, "iris_gnb_1.0.joblib")

[0 2 0 1 0 0 2 2 0 2]
[0 2 0 1 0 0 2 1 0 2]
90.0


['iris_gnb_1.0.joblib']

# LDA

In [4]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(x_train, y_train)
pred = lda.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(lda, "iris_lda_1.0.joblib")

[0 2 0 1 0 0 2 1 0 2]
[0 2 0 1 0 0 2 1 0 2]
100.0


['iris_lda_1.0.joblib']

# QDA

In [5]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda = QuadraticDiscriminantAnalysis()
qda.fit(x_train, y_train)
pred = qda.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(qda, "iris_qda_1.0.joblib")

[0 2 0 1 0 0 2 1 0 2]
[0 2 0 1 0 0 2 1 0 2]
100.0


['iris_qda_1.0.joblib']

# KNN

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier(n_neighbors=5)
knc.fit(x_train, y_train)
pred = knc.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(knc, "iris_knc_1.0.joblib")

[0 2 0 1 0 0 2 1 0 2]
[0 2 0 1 0 0 2 1 0 2]
100.0


['iris_knc_1.0.joblib']

# SVM

In [7]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
pred = svc.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(svc, "iris_svc_1.0.joblib")

[0 2 0 1 0 0 2 1 0 2]
[0 2 0 1 0 0 2 1 0 2]
100.0


['iris_svc_1.0.joblib']

# Regressão logística

In [8]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='newton-cg')
lr.fit(x_train, y_train)
pred = lr.predict(x_test)
print(pred)
print(y_test)
print((accuracy_score(pred, y_test))*100)
joblib.dump(lr, "iris_lr_1.0.joblib")

[0 2 0 1 0 0 2 1 0 2]
[0 2 0 1 0 0 2 1 0 2]
100.0


['iris_lr_1.0.joblib']